version: 0.2
env:
  variables:
    ECR_REPOSITORY: "072100331905.dkr.ecr.us-west-2.amazonaws.com/pf-fabric-dev-poc-helloworld"
    BASE_VERSION: "0.1.0"
phases:
  install:
    runtime-versions:
      dotnet: 3.0
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
#      - DOCKER_IMAGE="${REPOSITORY_NAME}_${BRANCH_NAME}_${BASE_VERSION}_${CODEBUILD_BUILD_NUMBER}_${COMMIT_ID:0:11}"
      - DOCKER_IMAGE=${REPOSITORY_NAME}
      - echo $DOCKER_IMAGE
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Installing .net core sdk 3.1
# ubuntu 18.04 image
      - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - dpkg -i packages-microsoft-prod.deb
      - add-apt-repository universe
      - apt-get update
      - apt-get install apt-transport-https
      - apt-get update
      - apt-get install -y dotnet-sdk-3.1
      - dotnet tool install --global dotnet-sonarscanner --version 4.8.0
  build:
    commands:
      - echo Build started...
      - cd src
      - chmod +x ./Host/nuget-setup.sh
      - ./Host/nuget-setup.sh
      - dotnet restore
      - dotnet build --no-restore
      - dotnet add UnitTests package coverlet.msbuild
      - dotnet test --no-build --logger trx --verbosity:normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:threshold=80
      - echo Building the Docker image...
      - cd Host
      - docker build -t $DOCKER_IMAGE .
      - docker tag $DOCKER_IMAGE $ECR_REPOSITORY/$DOCKER_IMAGE
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY/$DOCKER_IMAGE
      - echo Done
artifacts:
  files:
    - ./src/UnitTests/TestResults/*
