version: 0.2
env:
  variables:
    DOCKER_IMAGE_LATEST: "pf-fabric-dev-poc-helloworld:latest"
    DOCKER_IMAGE_VERSION: "pf-fabric-dev-poc-helloworld:v1"
    DOCKER_USERNAME: kishoryadav
    DOCKER_PASSWORD: DockerWorks1!
phases:
  install:
    runtime-versions:
      dotnet: 3.0
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD https://index.docker.io/v1
#      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
#      - $(aws ecr get-login --region $AWS_REGION)
      - echo Installing .net core sdk 3.1
# ubuntu 18.04 image
      - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - dpkg -i packages-microsoft-prod.deb
      - add-apt-repository universe
      - apt-get update
      - apt-get install apt-transport-https
      - apt-get update
      - apt-get install -y dotnet-sdk-3.1
  build:
    commands:
      - echo Build Started on `date`
      - cd src
      - echo Restoring packages...
      - dotnet restore
      - echo Building solution...
      - dotnet build --no-restore
      - echo Running unit tests...
      - dotnet test --no-build --verbosity:normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:threshold=80
      - echo Build completed on `date`
      - echo Building the Docker image...
      - cd Host
      - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_LATEST .
      - docker tag $DOCKER_USERNAME/$DOCKER_IMAGE_LATEST $DOCKER_USERNAME/$DOCKER_IMAGE_LATEST
#      - docker build -t $DOCKER_IMAGE_LATEST -t $DOCKER_IMAGE_VERSION .
      - echo Done building the Docker image
      - echo Pushing the Docker image...
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_LATEST
#      - echo Done pushing the Docker image...
artifacts:
  files:
    - ./src/UnitTests/TestResults/*
